### ISSUE TITLE
cargo build failed due to protoc binary not found

### ISSUE THREAD

**Issue by Tangziyi1** [hkbudb/vchain-demo#1]
error: failed to run custom build command for `exonum-proto v0.13.0-rc.2`
Caused by:
  process didn't exit successfully: `C:\Users\28027\Desktop\rust_code\vchain-demo-master\target\debug\build\exonum-proto-3ba79c628a81f6f5\build-script-build` (exit code: 101)
  --- stdout
  cargo:protos=C:\Users\28027\.cargo\registry\src\github.com-1ecc6299db9ec823\exonum-proto-0.13.0-rc.2\src/proto

  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', C:\Users\28027\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-2.24.1\src\lib.rs:203:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by xu-cheng** [comment]
You need to install protobuf in your system.

**Comment by DCMinds** [comment]
I have added protobuf as dependency in cargo.toml,  but still getting the same error.
@xu-cheng , Canyou please let me know how we have to install the protobuf
Please provide the steps or list of commands to run
